import type { Metadata } from "next";
import { Roboto, Roboto_Mono } from "next/font/google";
import "./globals.css";
import FooterSection from "./sections/FooterSection";
import Navbar from "@/parts/Navbar";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  display: "swap",
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="m-0 bg-white p-0">
      <body
        className={`${roboto.variable} ${robotoMono.variable} relative w-screen overflow-x-clip bg-white antialiased`}
      >
        <header className="relative w-screen overflow-x-clip">
          <Navbar></Navbar>
        </header>
        {children}
        <footer className="relative w-screen overflow-x-clip bg-[#141414]">
          <FooterSection></FooterSection>
        </footer>
      </body>
    </html>
  );
}
